//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoNFeCSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoNFeCSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icons8_Windows_8_Programming_Watch {
            get {
                object obj = ResourceManager.GetObject("Icons8-Windows-8-Programming-Watch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NFSE]
        ///
        ///;CIDADE=UBERLANDIA
        ///; CIDADE=MANDAGUARIPR
        ///;CIDADE=JUAZEIROBA
        ///HORTOLANDIASP
        ///CIDADE=PORTOALEGRERS
        ///CNPJ=03979726000106
        ///InscricaoMunicipal=118787
        ///
        ///
        ///NomeCertificado=CN=GRAFICA CINELANDIA LTDA:61148045000100, OU=AR SERASA, O=ICP-Brasil, C=BR, S=SP, L=SAO PAULO, E=, SE=25 6A 4F 3D E9 B0 62 F5
        ///
        ///; CpfCnpjRemetente=73418386000120
        ///; RazaoSocialRemetente=MN PUBLICIDADE AR LIVRE LTDA
        ///; QuantidadeRps=1
        ///; CodigoCidadeRemetente=3513009
        ///;CIDADE=FLORIANOPOLISSC
        ///;NomeCertificado=CN=TECNOSPEED SA:08187 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nfeConfig {
            get {
                return ResourceManager.GetString("nfeConfig", resourceCulture);
            }
        }
    }
}
